### ISSUE TITLE
Subtasks

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#11]
As a user, after submitting a task, I want an option to add sub-bullets in WF.

E.g.

First message
`Water the plants
`
Second message
```
+ take out the dog
+ do laundry

```
Third message
`+ Return book to library
`
Would create one top bullet with 3 subbullets

- Water the plants
--- And take out the dog
--- do laundry
--- Return book to library

There is only one sub-level supported, not 2-level nesting.

The first time a message doesn't start with "+" then a fresh new bullet is created.

**Comment by assafza** [comment]
duplicate #51
