### ISSUE TITLE
#Hashtag to assign a task to a project

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#12]
This example uses "#zendmode" as a specific hashtag. I can be any project name. Case-insensitive. Can contain a dash or underscore, e.g. "#buy-car" or "#water_plants".

User: 

#zenmode Add Airplane Modea adsf adsf adsf ds

Bot:

I noticed you used a *#zenmode* hashtag. If you would like to assign it to a dedicated *zenmode* list, please paste here the internal link for that list.

If the user's next message is NOT a workflowy link, then this flow aborts, and we continue adding items to the *default* list.
If the user's next message IS a workflowy link, then the association between the *#zenmode#* hashtag and the specific link is maintained, and future items are automatically stored under the *#zenmode* project in WF.

We only look at the first hashtag in a message, and only in the beginning of the message, not the middle.

**Comment by liatzionimorad** [comment]
We agreed on the following:
I noticed you used a #בודקת hashtag. 
What would you like to do?
1.To assign it to a dedicated בודקת list, please paste here the internal link for that list
2.To add #xxx and text followed to the default list


If the user chose option 1 ( a dedicated list ) and provided a valid internal link :
1. all text should be inserted to workflowy including #text. for example, user sent to bot :#work write a detailed description -> workflowy data will show #work write a detailed description
2. If the user-provided no text in addition to #xxx and provided an internal valid link the bot should save the link to this list and state : Assign of #xxx to link created
#work 

In case #urgent is used the same menu should appear the first time used.
3 exceptions regarding #urgent:
1. User is notified upon items in this list ( as defined in #3 )
2.  the word #urgent will not appear in the list 
3. the link to the list will pear in the end of the list

**Comment by ripper234** [comment]
If the user types `#xxx` without any other text - this will be interpreted as "defining or redefining the URL for project #xxx"

The bot will answer

`I noticed you used a #xxx hashtag. If you would like to assign it to a dedicated xxx list, please paste here the internal link for that list (ignore in order to continue normal operation).`


Both in this case, and in the case where the user's message has other text (e.g. "#xxx my cool task") - **if the replies with anything other than a Workflowy link, then the item is added to inbox as usual** .
