### ISSUE TITLE
Define KPIs for success/failure

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#18]

**Comment by ripper234** [comment]
This is for the entire Fredo project - how can we know if it's a success or failure. OKRs etc.

**Comment by ripper234** [comment]
@liatzionimorad I upped the priority on this to 1. Let's discuss in one of our next meetings.

**Comment by assafza** [comment]
We have defined the KPIs and working to get the events in mixpanel to support those KPIs and present them on a dashboard
#88
