### ISSUE TITLE
Change commands behavior

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#22]
We want the following changes:
1. an "/" should appear before any command to indicate this is a command ( !help , !logout,!cancel ,!bug,!inbox)
2. The command should only apply upon single word usage:
right:
!cancel
wrong:
!cancel now

if there are additional words after command the bot should relate as error and print the following:

"This command is not recognized (re type the line user wrote)"
and print the help menu

As a result of this change, the help menu changed ( see #7 ) and the Wellcome messages should change to include "!"
![image](https://user-images.githubusercontent.com/79567202/147731925-99247e14-b9d7-4107-a61f-b904517f190d.png)
change to "!help"

**Comment by liatzionimorad** [comment]
"/cancel"
 suggested by Dev as standard usage
@ripper234 - ok?

**Comment by ripper234** [comment]
Yep
