### ISSUE TITLE
!listmaps command - returns a list of all existing mappings for this user

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#28]
`/listmaps`

This commands returns a list of all current mappings, from #KEYWORD to WF Link

Sample outputs:

1.
`"No maps exist yet, please enter an Internal WF link to configure your default map"
`
2.
`<default> --> https://workflowy.com/#/762aaea2dce3
`
3.
```
<default> --> https://workflowy.com/#/762aaea2dce3
#urgent --> https://workflowy.com/#/51223ffaf
```

4.
```
<default> --> https://workflowy.com/#/762aaea2dce3
#urgent --> https://workflowy.com/#/51223ffaf
#car --> https://workflowy.com/#/10123222f
#מכונית --> https://workflowy.com/#/10123222f

```

**Notes**
1. In example 4, both #car & #מכונית map to the same WF link
2. The same keyword cannot appear twice. A single map cannot appear **#car** twice.

**Comment by liatzionimorad** [comment]
same as #21 
I think should get high priority

**Comment by ripper234** [comment]
I'm not sure if needs  high priority, but - this should be relatively easy to
implement. So, if easy --> then high priority.  





On Sun, Jan 2, 2022 at 10:42 AM liatzionimorad ***@***.***> 
wrote:


same as #21
I think should get high priority

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>



Ron Gross+972-52-6558841ripper234.com  |  burner.vc  |  emailcharter

**Comment by liatzionimorad** [comment]
This command should be added to the help menu:
7. /listmaps- returns a list of all current mappings.
