### ISSUE TITLE
Automated Monitoring

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#30]
אבל, אני רוצה שנסתכל על דברים בניתוח סיסטמי של 5 whys.
מכירה?

https://he.wikipedia.org/wiki/%D7%97%D7%9E%D7%A9_%D7%A9%D7%90%D7%9C%D7%95%D7%AA_%D7%9E%D7%93%D7%95%D7%A2

כלומר, אני לא רוצה רק שנפתור את הבעיה הטכנית הנוכחית. אלא שנבין את השורש, ונוודא שבעיות דומות לא חוזרות בעבר. ובמקרה הספציפי הזה, כבר היו תקיעות בעבר.

כלומר, אני רוצה ש (בשבוע הבא, שוב - לא לחוץ לסופש :) ):

1. נאבחן מה גרם לבעיה הנוכחית ונפתור. ואני לא רוצה לשלוח להם עוד מידע ולוגים (לא נוח לי לעשות את זה כל הזמן משיקולי פרטיות, וגם כשדברים יקרו למשתמשים אחרים, אנחנו צריכים יכולת אבחון טובה בלי שהם ישלחו לנו היסטוריה שלמה). אלא במקום, אני רוצה שהם יאבחנו עם כלי הלוגים שקיימים להם. ואם חסר להם מידע, שיוסיפו לוגים כך שלפעם הבאה יהיה קל לאבחן.

2. וגם, ניצור מערכת שבאופן אוטומטי מתריעה (אצלי, אצלך, אצל המפתחים) כשהיא נכנסת למצב "תקוע". אני לא רוצה שזה יחכה עד שמישהו ידווח שיש בעיה, אל
https://he.wikipedia.org/wiki/%D7%97%D7%9E%D7%A9_%D7%A9%D7%90%D7%9C%D7%95%D7%AA_%D7%9E%D7%93%D7%95%D7%A2

**Comment by liatzionimorad** [comment]
We want an automatic test running to conduct the following:

Once a day send a message to the bot writing random  text to default list defined ( user should already be connected and known)
Verify :
Bot approved
data saved to WF
In case of failure or no response : restart server , re-run test, if still nonoperative send mail to liat@2be.org.il
@ripper234  please comment

**Comment by ripper234** [comment]
I think the test should be once every hour or 3 hours, not once a day.

This is a sanity test. There should be more tests coming after this one, but let's start with a sanity test.

And in case the test fails - I don't think we should restart the server automatically, but rather raise a signal to something like PagerDuty.com. A system where the servers constantly need restarting is not a well-built system. Let's understand the issues and design the system itself to be fault-tolerant. I'm not ruling out a possible auto-restart as a patch, but it's not a good method - let's try to start without it.

PagerDuty can try to reach multiple team members via some order, SMS/Email/Phone call via some escalation policy.

**Comment by liatzionimorad** [comment]
@elihaidv  please respond here

**Comment by liatzionimorad** [comment]
@sgino209  input :
Motivation is clear, for ensuring system health and increasing its fidelity and overall stability. You might consider a softer (less intrusive) approach, at list to start with, based on Coralogix (or similar..) services, based on sniffing the system backlogs and alerting when necessary.

**Comment by liatzionimorad** [comment]
@elihaidv  please refer to the recommendation is it possible to use
https://coralogix.com/
solution based on logs nonintrusive to users traffic

**Comment by lotem-vanunu** [comment]
i checked coralogix.com,
we can use their RestApi , becase they dont have sdk for php.
our server will save important user actions in file, and with const interval send the logs to coralogix.
 we can save actions like login, error, request to workflowy etc.

**Comment by liatzionimorad** [comment]
@sgino209  please review

**Comment by sgino209** [comment]
I see that the @lotem-vanunu reviewed the Coralogix option, and confirmed it’s feasible from his side. 
That’s good, recommend to go ahead and drain the important events over their REST API. 
We’ll then have a high flexibility of programming rules and notifications events (on Coralogix).
I recommend to log users data only in a DEBUG verbosity, for reducing logging load and for respecting users privacy. We may apply a DEBUG verbosity for ramping-up (few initial months), then later on switch for an INFO verbosity, once the system scales up and becomes more mature.
