### ISSUE TITLE
Image handling

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#31]
We want to limit the image use in the following way:
1. Do not enable image > 500k if the user sends a message over this size please notify "Error. Image is not saved since size should not exceed 500k"
2. User should be able to store up to 50 images. In image 49 users should get a message:
 "Please notice: You save 49 images. are about to exceed max images of 50. 
Image 51 will be lead to deletion of image#1'

and we should act according to it.

To Dev:
please check current cloud size so we can better estimate/

@ripper234 please review messages

**Comment by ripper234** [comment]
"Images above 500k are not supported"
"Please notice: You stored 49 images out of max 50"

**Comment by liatzionimorad** [comment]
אליחי יעדכן הצעה

**Comment by elihaidv** [comment]
Cloudinary max free storage is 25GB
