### ISSUE TITLE
#listname_notext

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#36]
In case the user enters #listname with no text following the bot asks if this is a list and requests for list link.

If the user typed 

#work

After the #work list was configured, then the bot should answer:

Type #work <text_to_remember>
in order to insert it into
<link to specific workflow list>

For example, if I write

#work

The bot will reply 
#work is already mapped to (link to list- https://workflowy.com/#/063cbf5acab8

Type #work <text_to_remember>
in order to insert it into

**Comment by ripper234** [comment]
This seems to be a bit off. @liatzionimorad can you re-read the text and fix as needed?

(BTW - the example should NOT appear as the bot output. It is just an example for the developers)

**Comment by liatzionimorad** [comment]
#work is already mapped to (link to list- https://workflowy.com/#/063cbf5acab8
Type #work followed by your text
in order to insert it into the list
