### ISSUE TITLE
Statistics / Analytics

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#37]
**Please provide a design of this feature before implementing.**

As an admin, I would like to receive a weekly report containing statistics.

Some example statistics:

1. New user signups
2. Total number of Messages added to lists
3. Number of active users (active user = sent at least 3 messages in the last 7 days)

Note - in the future we'll probably want many more analytics.
We should make sure to maintain a log of all relevant actions. (The log should not contain the message content itself, just metadata)

We need to decide where to store the raw analytics data.
In the DB? In a separate DB? In Google Analytics?
How is the report pushed to admins?
(Whatsapp message? Email? Web page?)

**Comment by ripper234** [comment]
GA is great.I think - let's start with a small implementation of this via GA and
get a feel for it + what's missing.
What's your time estimate for an initial delivery here?  





On Mon, Jan 17, 2022 at 2:14 PM elihaidv ***@***.***>  wrote:


The simplest solution is to use Google Analytics for this.
I can send events to it
It organize the data in comfort display, and you can export several reports.
You can enter to this site every time you want

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>



Ron Gross+972-52-6558841ripper234.com  |  burner.vc  |  emailcharter

**Comment by elihaidv** [comment]
OK.
To start I need:
- a GA account.
- List of all events do you need to log.
For example:
1. First message from user
2. Urgent message
3. Regular item
4. New hashtag

Also we can use Firebase Crashlytics to monitor errors in the bot.

**Comment by ripper234** [comment]
1. Can you create the GA account for us?2. Regarding the list - can you talk
with Liat  for 10 minutes and close this with her? It doesn't have to be
perfect, we'll add more events later as needed.  





On Wed, Jan 19, 2022 at 7:20 PM elihaidv ***@***.***>  wrote:


OK.
To start I need:

 * a GA account.
 * List of all events do you need to log.
   For example:

 1. First message from user
 2. Urgent message
 3. Regular item
 4. New hashtag

Also we can use Firebase Crashlytics to monitor errors in the bot.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>



Ron Gross+972-52-6558841ripper234.com  |  burner.vc  |  emailcharter

**Comment by liatzionimorad** [comment]
Although Google Analytics typically rises-up as a “default” option for such purposes, it might be an overkill, in terms of maintenance complexity. It can take a lot of time and expertise to get a full, accurate picture of your metrics. I think it is worth considering AppsFlyer or MixPanel as alternatives

**Comment by liatzionimorad** [comment]
@JerryVDP  which statistics are you going to collect from there?

**Comment by JerryVDP** [comment]
@liatzionimorad 
The system will broadcast two types of events:
1. New user event
2. Message event (each time a user sends a new message)

Then we'll create a dynamic report on MixPanel that will show statistics for active users based on those 2 events types. That way we'll achieve the original requirements of calculating the statistics for new users, total messages, and active users (see original post).

**Comment by liatzionimorad** [comment]
@sgino209 please review

**Comment by sgino209** [comment]
I think that MixPanel is a good choice, mainly in terms of features, complexity and scalability. 
I believe that Fredo will include some more advanced NLP in the near future, and then the analytics will have to be enhanced, e.g. with logging the users' intents and entities. That could also be a baseline for powerful data-science activities, e.g. smart assistance, recommendation system, anomaly detection, etc. 
I’m mentioning all of that here, for highlighting that the analytics architecture must be robust enough for easily adding new events as we go. Please ensure that.

**Comment by JerryVDP** [comment]
@sgino209 
Thanks for the feedback.
I can confirm that the infrastructure is robust and scalable, both in terms of functionality and in terms of implementing an analytics provider (if someday in the future we choose to go with a different provider other than MixPanel it will be much easier to implement).

**Comment by assafza** [comment]
@liatzionimorad can you please share with me credentials for Mixpanel. I want to test this.
Or you can add me as a role there assaf@papayaapps.io

**Comment by assafza** [comment]
@elihaidv @JerryVDP 
I have few questions:
1. When do send the "NEW_USER" event to Mixpanel? What is the trigger?
2. I see a lot of phone numbers (60 unique numbers), are they used as a test? see the report here:https://bit.ly/3IRFSdT
3. we will need a way to differentiate the testing data from the real data. I suggest using a separate project in Mixpanel for
    this purpose. See the additional project I created: https://mixpanel.com/report/2661337/settings/#project/2661337
    Every time we release we need to make sure that the tokens being used are for the production Mixpanel project.

**Comment by JerryVDP** [comment]
@assafza 
1. Whenever a new user is created, which means whenever a user sends a message for the first time.
2. You're correct, the test also triggers those events.
3. @elihaidv Please change ANALYTICS_MIXPANEL_TOKEN in the production and staging .env file to this one: 55389bbd8b423ff4628a637ffd12589c
