### ISSUE TITLE
Remove the need for WF user & password

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#39]
**Needs Design/Research/Estimation**

I believe there should be a way not to require a User and Password from our Workflowy users.

If we can do this in a seamless way, this is **super important and valuable**.
Users do not need to overcome a "fear barrier" of giving us this data.
And we won't have to worry about how to securely store it.

Instead of users sharing the Internal Link to their lists, the users can just Share a list of Workflowy, and send us the Share Link. I don't know if the existing WF access package we're using supports Share Links - but even if it does not - we can parse the HTML ourselves and simulate a user (or possibly we can enhance the open-source WF library we're using, to include this functionality).

Let's do some research and estimation on what it would mean to implement this feature, both in how the usage would work, and what would be the cost & risks to develop.

**Existing login mechanism**
I think that if we decide to develop this, we might want to deprecate and eventually the existing login/credentials mechanism.

1. New users should not be prompted for passwords, but only for the Share Links
2. Existing users would be migrated to the new method (and reminded that it's best they change their workflowy password, for security reasons)
3. Eventually, we'd like to delete the password column from the users table.

**Comment by liatzionimorad** [comment]
will forward to the team

**Comment by elihaidv** [comment]
Currently passwords are not stored in our DB.
For what I saw, free users cannot share a link with edit permissions. Only read-only link.
But they can give access to specific user.

My suggest is to create a general account. All users will need to share with it their lists.
The bot will receive the emails and will accept the invitations.

Maybe it can be done one time. Because out bot given access to all sub lists.
So user can give us one main list and refer only to sub lists.

Another idea is to it in opposite.
Our bot will create a list and give the user access,
It can be more simple to develop and more clear to user

**Comment by liatzionimorad** [comment]
@ripper234 , @sgino209  please share your view on suggested solutions.

**Comment by liatzionimorad** [comment]
shahar's input : 
Two options were suggested:
1.	User will share their parent-lists with the Bot
2.	Bot will share his parent-lists with the users
The motivation for this issue is clear. I find the 2nd option more robust and easier to maintain. We’ll have to assure that the existing user lists can be automatically and seamlessly migrated as sub-lists under the new hosting list provided by the Bot.

**Comment by ripper234** [comment]
@liatzionimorad tested this, and free users can definitely share lists.

@elihaidv @sgino209 please review.

**Comment by ripper234** [comment]
Option 2 is not good enough, users need the flexibility to share any lists, not just those inside a list that the bot shares with them.

What's involved in doing number 1? Can we estimate the feature?

**Comment by liatzionimorad** [comment]
Liat+Shahar
the assumption is that sharing a list with edit permissions with another WF account can replace legacy authentication ( user name+ password)
@elihaidv - is this assumption correct ?

If the answer is yes the preferred solution should be what you suggested 
"My suggestion is to create a general account. All users will need to share with it their lists.
The bot will receive the emails and will accept the invitations."

This means to our understanding 
1. User will go to WF and copy the desired list url
2. !SHARED_LIST_WITH_BOT < list_url> 
note in phase the user will automatically grant access to the specific user ( bot ) 
3. process will continue as today (user is logged in by this process)
@elihaidv  please confirm we understood well :-)

**Comment by liatzionimorad** [comment]
the above solution can also provide an answer to #16

**Comment by elihaidv** [comment]
Just  update the progress of work:
1. The bot can receive external link, and attach the list to its account.
2. The bot can update others' lists

Need to do:
1. Develop the process of sharing the link by user. (I need an explanation how to do this )
2. Fix problems with edit shared list

**Comment by liatzionimorad** [comment]
@elihaidv Not clear to me if something is needed from us
Not clear to me - what exists in the API and what are you developing on top and weather it will be a part of API or bot

**Comment by elihaidv** [comment]
Exists in the API:
 - Edit own lists

My development (Currently in test):
 - Attach shared list to user's account
 - Edit shared lists
 
 Needs from you:
  - Create a general user for Fredo
  - Build scenario of the first login, and map new lists (Messages, Screenshots, etc)

**Comment by assafza** [comment]
Hi I have created a new flow based on the following requirements:
1. New shared lists logic that doesnt require password
2. Allow users to select more than 1 platform (the flow offers it as a test not as an actual developed feature, for the sake of testing and validating the idea of new platforms as an MVP)
3. Existing users will need to replace their list mapping with the new share logic

You can find the flow here:
https://miro.com/app/board/o9J_lttkfEA=/?invite_link_id=983331365689

Tutorial video to be played as a gif:
![WorkFlowy_-_Organize_your_brain__-_15_February_2022_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/25544824/154074020-839d4100-b748-457f-ae45-cb41c0b25165.gif)

**Comment by liatzionimorad** [comment]
@assafza   it was not clear for a new user that a default list needs to be defined again so we changed the following:
![image](https://user-images.githubusercontent.com/79567202/154263623-a2e7f3a8-871f-4efe-8bab-7cb8e569fbe7.png)

A line will be added at the bottom that will state:
 We will now ask you to to redefine your default list .

From this point on the flow is identical to new user.


![image](https://user-images.githubusercontent.com/79567202/154264013-06130e8c-57a4-40a3-9472-b433fb73af47.png)


please  update the miro :-)
