### ISSUE TITLE
[Website] Add a simple form to the fredo.ai website 

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#41]
Note, this is not a development task, but for @liatzionimorad  / our web guy.

We should add a quick form to the website, that lets a user tell us:

1. Their email
2. Messenger platform  (choose from a list and/or custom text field)
3. Task Management system (choose from a list and/or custom text field)

And then we will email the user when we implement their messenger platform and/or task management system.

We need to write the correct Copy/text here. Liat, maybe you can prepare a draft version, and review it with one of the translators you used in the past?

**Comment by liatzionimorad** [comment]
Got it .
Will start with a translator and move forward from there.

**Comment by liatzionimorad** [comment]
Got it

**Comment by ripper234** [comment]
Website should contain a button/link **get notified when we add your favorite messenger/task tool** . This leads to a Google Form.

https://docs.google.com/forms/d/1bkN0N7afG9n5S6t8ULQs9lFiixz0OxBrAWOkSQc_UUs/

Liat - can you [register to get email notifications](https://support.google.com/a/users/answer/9308874?hl=en) whenever anyone fills this form? (and let me know from time to time)
