### ISSUE TITLE
whatsapp<->google keep

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#43]
We need to check the option of referring fredo from whatsapp to google keep.

Please evaluate what is needed for the following functionality:
1. log in
2. enter a note
3. enter a list
4. enter items to an existing lit
5. creating "urgent" list
6. saving images and audio

@ripper234 take a look if any additional functionality needed at this stage

**Comment by ripper234** [comment]
Should be automatically implemented by Email integration #42  - at least in the "write to Keep" direction.

**Comment by ripper234** [comment]
https://www.alphr.com/send-email-google-keep/

**Comment by ripper234** [comment]
This is good to go from my end (up to dev priorities).

**Comment by liatzionimorad** [comment]
@sgino209 stated the same:
It indeed seems that the Email integration will do the trick (Issue 42), since Google Keep already supports notes invocation triggered by incoming emails (link). Hence, instead of sending the data to the user’s email, we’ll send it to it’s Google-Keep proxy. Need to further explore read direction, i.e. pulling out notes data from Google-Keep.

This should be the direction

**Comment by ripper234** [comment]
Increasing to priority-2 because email integration should make this easy to implement.

**Comment by assafza** [comment]
I must say that I couldn't understand how this would be implemented technically. the video shows a manual work needed from the Gmail account to add it as a note to keep.
I am probably missing something.

In any case, I have added a flow to Miro to support this:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764519686428964&cot=14
<img width="492" alt="Screen Shot 2022-02-24 at 13 59 23" src="https://user-images.githubusercontent.com/25544824/155519889-7b71eeae-6904-441a-a64c-59a5fe4dfdb8.png">

**Comment by assafza** [comment]
@elihaidv please validate the ability to send easily notes to Keep by sending an Email.

**Comment by assafza** [comment]
@elihaidv Have you checked the above? wanted to know if this is really straight forward.. thanks

**Comment by assafza** [comment]
@elihaidv @JerryVDP any news on that issue?
(cc @liatzionimorad)

**Comment by assafza** [comment]
Thanks @JerryVDP 
Closing this and we will make a decision soon based on issue #85
