### ISSUE TITLE
Change Github repository icon

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#48]
https://github.com/organizations/WA-WF-Bot/settings/profile

![image](https://user-images.githubusercontent.com/172282/151161479-c979ac97-7d70-4851-bcd4-88d705907cc4.png)

**Comment by liatzionimorad** [comment]
did it- I cant see the change!
@ripper234

**Comment by liatzionimorad** [comment]
טוב התעדכן
