### ISSUE TITLE
Email interface - the next step?

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#57]
Email features (priority 3 - let's discuss, let's get feedback from Asaf)
Do these match our general product line? Or are there just "cool features" that don't really mesh with what we're doing.
Email interface changes
Send email: "Remind me in 3 days to call Shira"
אני רוצה לשלוח מייל לפרדו, ושיזכיר לי בזמן מסויים לעשות אותו. האם זה כפילות עם םיצר אחר? לא בטוח.
Email to Google Calendar or Google Reminders integration

We need to discuss with @assafza

**Comment by assafza** [comment]
BTW the same will work with the "Other" option to learn what users actually want:
<img width="265" alt="Screen Shot 2022-02-14 at 16 19 52" src="https://user-images.githubusercontent.com/25544824/153881302-34eedc79-c189-4fc1-af5c-76e6536f99ea.png">

**Comment by ripper234** [comment]
Another usecase here:

I want to send an email to bot@fredo.ai, and have the content of that email sent to me via Whatsapp.

I want to define automatic rules/filters on gmail, and have urgent/important emails bounce to my whatsapp via Fredo.

Gmail-specific
Maybe in the future I'd like to give Fredo access to my Gmail (specifically Gmail for now), and have Fredo **poll** my email 1-2 times a day, and search for urgent emails (urgent = defined via some filter). It can then notify me via Whatsapp about urgent emails that are still in my inbox (or still "unread", for people not using Zero Inbox).

This is similar to how today in Workflowy, it polls the Urgent list and notifies me if this list has items, twice a day.
