### ISSUE TITLE
Automatically create list maps

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#58]
As a user I want to have all my lists mapped automatically to be able to easily use the shortcuts. 

At the moment, I understand a user needs to explicitly mention his own #hashtag to a list in order to have it mapped.
I see the problem here in few aspects:
1. It is hard to understand and also creates confusion
2. It creates more work for the user
3. If the list name is changed or the hashtag is changed in the WF platform it doesn't reflect in the bot when you list the maps

My suggestion:
once the user is sharing a list with Fredo the #hashtag of this list should be automatically aded to the list.
Example: I shared with Fredo a list called "Personal notes" -> automatically create "#personal_note" hashtag

**Comment by ripper234** [comment]
If I understand correctly, you mean to suggest that Fredo will take the list Display Name from Workflowy, and translate that to a #hash - correct?

I'm not sure if this this serves the need. The user needs a very fast & short way to access the list. While - when viewing it in Workflowy, they want a more detailed, longer display name / list name.

We could have Fredo extract any #keywords from a list name or its attached note (see Workflowy Notes - Shift Enter to edit them).
