### ISSUE TITLE
More welcoming onboarding for new users

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#6]
Let's go over the onboarding - start of conversation with the bot for a new user, and make sure that it's user friendly and self-explanatory.

1. All the wording should be refined.
2. The bot asks to "sends us the list" ... should be clear what list, is internal link required or not, etc. Maybe a nicer welcome message at the top.
3. Anything else?

**Comment by liatzionimorad** [comment]
Current messages:
Welcome to Whatsapp->Workflowy bot 🤖
User name and password are required.
Please enter user name:
Please enter password
![image](https://user-images.githubusercontent.com/79567202/144831926-834f52a0-ebe3-4dd7-81ae-400f9f610a7c.png)

Next the message is:
Please paste list link
next message: the list was found. Please add item to the list

Suggested:
Welcome to Whatsapp->Workflowy bot
After logging in to your workflowy account and providing a list link every message you send will be written in your workflowy list.
Please notice:
A message is limited to 1024 characters.
You can press "logout" and the process will be terminated, you will return to login phase.
You can press" help" or "Help" to open the help menu.
 
To start, please enter your workflowy user name:


Please enter workflowy password:
![image](https://user-images.githubusercontent.com/79567202/144831937-561ff98f-d8b6-4c2b-a139-0c96d723df7c.png)

Next message:
Please paste a link to the specific list you want to write to
The link should be "internal link" ( can be retrieved from list menu - copy internal link)

The next message suggested:
The list was found. Every message you send will be added to this list until you logout.
You can start sending messages!
@ripper234  Please comment

**Comment by ripper234** [comment]
Welcome to Whatsapp->Workflowy bot 🤖
I help you quickly offload tasks from your brain into your favorite task management system.

(Currently only Whatsapp & Workflowy are supported)

To start, what's your Workflowy username?

---

Sweet. Now, in order to connect to your account, I need your Workflowy password. Don't worry, I'll keep it securely.

---

Great success!
Now, please paste the *internal* link to your inbox on Workflowy.

![image](https://user-images.githubusercontent.com/172282/145187400-e9a8683b-0def-47b8-97ea-4c2d84bbac33.png)

---

Awesome, you are all set up.
Every message you send me will automatically be added to your WF inbox.
Try it now - try sending me a "test" task now.

--
**<Automatic response from the bot>**
--

If you get stuck or want to explore, try the "help" command.
