### ISSUE TITLE
Urgent reminders are sent even when no urgent tasks exists

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#60]
I just got this message:

![image](https://user-images.githubusercontent.com/172282/154122187-6f52fa94-89b4-4cdd-8c36-fc3bfaa45c92.png)

This is my urgent list:

![image](https://user-images.githubusercontent.com/172282/154122251-11e951ff-1967-4827-92c4-7021f4cbd748.png)

( https://workflowy.com/#/215ded177273 )

It contains 78 items, all main items checked off.
Maybe some child items are not checked off?
(See "Give Rob Scribe my Whatsapp" - not checked off)

I'm not sure what's the exact state / how to reproduce.
The desired behavior is for the message to be sent only if there are **visible child bullets**.
So - if all the top-level child bullets are checked off - the message should not be sent.

![image](https://user-images.githubusercontent.com/172282/154122857-ee6c07bf-2b72-46d1-84a4-41850f6da494.png)

**Comment by assafza** [comment]
@elihaidv please assign this to the correct person when you get a chance. thanks
