### ISSUE TITLE
Bot should initialize before user sends anything

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#63]
Currently I needed to send the bot any text to get the welcome message.
This is wrong practice since right at the beginning we already make the user think what he should do.

Our goal is to minimize the uncertainty and lead the user towards success (success = send his first text that will go to either email or WF)

<img width="910" alt="Screen Shot 2022-02-24 at 14 27 16" src="https://user-images.githubusercontent.com/25544824/155524405-7f4453f2-383b-4431-b257-ffde46a64ab0.png">

**Comment by liatzionimorad** [comment]
cannot be done
