### ISSUE TITLE
Click "try again" when user shared a wrong link

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#67]
When user click on "Try again" button we should direct him better what should be the next steps.
In order to make the process clearer lets chenge the text and action buttons:

<img width="895" alt="Screen Shot 2022-03-01 at 10 36 30" src="https://user-images.githubusercontent.com/25544824/156142660-d2bef103-f3a3-47f7-9c72-356eb113e57d.png">

**Comment by liatzionimorad** [comment]
@elihaidv  not done yet
