### ISSUE TITLE
First shared list should automatically be added as a default to list map

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#69]
As a user I would want the ability to see the connected lists to know to which lists I am adding tasks to.

Once I connected and shared the first list it will be added into my list map as the default list.

Currently I see that /listmaps command is empty and adking for asking for an internal link(old method)

It should work as followed:
When user shared the first shared link it should be added as a **default**  and be output of /listmaps command

currently:
<img width="891" alt="Screen Shot 2022-03-01 at 13 40 42" src="https://user-images.githubusercontent.com/25544824/156163120-eb1fa25e-17e0-4e27-8375-0cf8505199d1.png">

**Comment by liatzionimorad** [comment]
Not done yet, @elihaidv
