### ISSUE TITLE
help menu

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#7]
When the user sends "help", they should get the help menu message.

Commands
1. ...
2. ...
3. ... Link to this repository for submitting issues.  (help menu should direct users to submit issues in this github repo)

**Comment by liatzionimorad** [comment]
Commands:
1. Logout\logout - will log you out from the workflowy and you will need to perform log in again. To activate the login message you can type any key.
2. Cancel\ cancel - will re-address you to list link phase.
3. Urget\urgent ...

**Comment by liatzionimorad** [comment]
add 5.*cancel* - returns to main menu
@ripper234  - is that ok ?

**Comment by liatzionimorad** [comment]
Changes required:
1. !logout - Logs you out from Workflowy and erases all your login details.
2. !inbox - Choose a different inbox folder in WF.
3.#urgent \ #דחוף - Start a message with #urgent to put it in an "urgent tasks" list in WF.
4. #your_list_name - By starting a message using "#__" you can place items to a specific list. This can be used for various lists you define.
5. !cancel - returns to the main menu
6.! bug Allows you to submit a bug report here
