### ISSUE TITLE
/inbox command fixes

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#70]
1. change the description in the help menu to "Choose a different list in WF to be set as the default shared list"
2. Change the flow: once user send **/inbox** system should check (# of mapped lists >1 )
    2.1    If TRUE (more than 1 default list is mapped) -> show the mapped lists and ask the user to select the **#list** from the 
            mapped lists. Also offer a way to create a new mapping (using a button "Connect a new list"- > when button is clicked show the 
            instructions to map a list.
    2.2   if FALSE ->  send the message with instructions how to share a list.

Should work as follows:
<img width="437" alt="Screen Shot 2022-03-07 at 11 50 07 AM" src="https://user-images.githubusercontent.com/25544824/157007873-a1574e7d-b09c-4c35-aab0-99e0151b2e08.png">

Link to the Miro flow:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764520359422733&cot=14

**Comment by liatzionimorad** [comment]
![image](https://user-images.githubusercontent.com/79567202/158581906-47b360af-6b6f-4cc4-ac52-0848b0cc04c1.png)

1. the writing should be go to main menu (English)
2. the command is not supported?
