### ISSUE TITLE
Confirmation for added message - new format

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#72]

**Comment by assafza** [comment]
When a new text is added to WF as a new item the confirmation message should be sent in the following format:
✅ "<text>" added to your "<list name>" list

in the given example below "Test" was added to Default list. the message should be ✅ "**test**" was added to your "**Default**" list

 This should replace the current message:
<img width="284" alt="Screen Shot 2022-03-01 at 13 19 03" src="https://user-images.githubusercontent.com/25544824/156159933-dc4e0a96-1f51-4e25-b9bd-12605a94499f.png">

**Comment by liatzionimorad** [comment]
@JerryVDP - it does not state correct list name...
![image](https://user-images.githubusercontent.com/79567202/156917423-12985160-5c0c-4709-8452-6cfd4a56b8e2.png)


please fix

**Comment by liatzionimorad** [comment]
worked well second time for list name in Hebrew
