### ISSUE TITLE
When typing /inbox it retrns to main menu and delete all data

### ISSUE THREAD

**Issue by liatzionimorad** [WA-WF-Bot/WA-WF-Bot-Public#74]
![image](https://user-images.githubusercontent.com/79567202/156918409-d73700db-86ba-44f2-a5e4-0702a078e5af.png)

![image](https://user-images.githubusercontent.com/79567202/156918424-2ed20819-9694-4d0f-9f3b-96badbecf34f.png)

**Comment by assafza** [comment]
This is issue will be handled as part of #70 - Archiving
