### ISSUE TITLE
/cancel command in help menu

### ISSUE THREAD

**Issue by assafza** [WA-WF-Bot/WA-WF-Bot-Public#76]
As a User I wish to have the ability to cancel and go back/reset my current operation or flow to avoid deadlocks.

To Dos:
1. add /cancel to the main help menu: 
    **/cancel** - Cancel current flow and connect you back to your Default list if exist
2. See the flow: once user send "/cancel" the system checks (# of lists >=1):
   2.1  if TRUE, cancel current flow and have the user at a point that any text he sends will be added as an item to Default list.
   2.2 if FALSE, take the user to onbparding message to connect his first list.
<img width="767" alt="Screen Shot 2022-03-07 at 12 06 52 PM" src="https://user-images.githubusercontent.com/25544824/157011352-b94b38b3-5f05-40c4-b632-5c4b168851ee.png">

Miro flow: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764520401445202&cot=14

**Comment by liatzionimorad** [comment]
This flow should apply whenever user decides to use it : typed a wrong list link\ evalid e mail\ any error state
