### ISSUE TITLE
Bot should update users whenever its version is upgraded

### ISSUE THREAD

**Issue by ripper234** [WA-WF-Bot/WA-WF-Bot-Public#8]
Release notes

**Comment by ripper234** [comment]
Only major features, not bug fixes.

**Comment by liatzionimorad** [comment]
Let's decide on:
1. Add release notes file
2. the base version as 1.0
3. Version content - First release of ToInbox. 
4. For future releases state only major issues:
5. Add support in audio file saving
6. limit image size to 500 k...


If a user is using the bot on a daily basis and the version was updated he will get the following message:
ToInbox Bot was updated to version 1.x

— Bug fixes and other minor improvements

Full version history is available here:
release notes link

**Comment by ripper234** [comment]
LGTM

==

Looks Good To Me
